### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by namtrah** [g-bauer/obsidian-quick-monsters#7]
I installed according to your instructions. I am using Obsidian v0.12.19. I receive the following console error when trying to activate.

    app.js:1 Plugin failure: quick-monsters-5e Error: ENOENT: no such file or directory, open 'C:\notes\.obsidian\plugins\obsidian-quick-monsters\main.js'
    
I presume I need to copy the contents of the src folder into the root of the git clone. But maybe it is a version problem with the plugin?

**Comment by g-bauer** [comment]
Hey! Yes installing the plugin means downloading `obsidian-quick-monsters-v0.6.0.zip` from the latest release, and unpacking the directory into your plugin folder. Inside the directory is the `main.js` file (together with the manifest).

I will check if the plugin works tonight and come back to this issue in case fixes are needed. I wanted to add some minor features and hopefully by the end of the year the plugin will be available from the community plugins tab.

Thanks for your interest ;)

**Comment by g-bauer** [comment]
@namtrah I tried installing the plugin in a fresh obsidian vault and it worked. I downloaded the zip file and extracted the directory directly into my plugin folder. Could you give it another try? Alternatively, you can try installing it via the [BRAT](https://github.com/TfTHacker/obsidian42-brat) plugin.

Let me know if that worked for you.

**Comment by namtrah** [comment]
> Inside the directory is the main.js file (together with the manifest).

Actually it is not. In side the obsidian-quick-monster-main directory is a directory called `src` and inside there is the main.js and the manifest is back one directory higher.

In a clean vault (nothing installed at all), safe mode off, zip file unpacked in .obsidian and Obsidian restarted, it still does not work. In fact the plugin is not even seen.

![image](https://user-images.githubusercontent.com/13903735/146564671-8a2881e2-735a-420f-a3d2-03827a063ba5.png)

**Comment by g-bauer** [comment]
Weird. Just to make sure - did you download the `obsidian-quick-monsters-0.6.1.zip` (**not** the `Source Code`) under the current release?
![Screenshot_20211217_170211](https://user-images.githubusercontent.com/7261278/146573425-b75450a7-0dfd-4271-bbe5-2b1a5620f4ae.png)

If I download that zip and open it, there are both the `main.js` as well as the `manifest.json`:
![Screenshot_20211217_170257](https://user-images.githubusercontent.com/7261278/146573512-2376a5c9-bc9f-42d4-9dee-936c8d5722e7.png)

**Comment by g-bauer** [comment]
Besides the `zip`, you can also download both files (`main.js` and `manifest.json`), make a directory and just paste both files into said directory. You can now also use BRAT to download and install this plugin.

**Comment by namtrah** [comment]
Well, I guess that was the problem. I downloaded the "zip" from the sources page. and using that it wasn't possible because manifest.json and main.js were in separate directories. 

After deleing everything and installing only the .zip file from the release section it seems to work just fine.

Thank you. You may want to clearly describe in your readme to take only the .zip file (and not sources.zip) from the Releases page to use until you are an accepted plugin. I didn't need the BRAT plugin. 

Thank you for your assistance. It really helped.

**Comment by g-bauer** [comment]
Awesome, I'm glad it works now. Thanks for bringing up this issue - I will improve the installation section of the readme.
