### ISSUE TITLE
[Feature request] BRAT support.

### ISSUE THREAD

**Issue by lukthony** [g-bauer/obsidian-quick-monsters#8]
The [Obsidian42 BRAT plugin](https://github.com/TfTHacker/obsidian42-brat) can be used to download third-party plugins not available on the community plugin store by inputting their source Github repository. This doesn't work for this project, giving the following error:
<img width="336" alt="Screen Shot 2021-12-16 at 7 43 22 PM" src="https://user-images.githubusercontent.com/65358837/146474921-9e7906e3-8a31-40fd-857a-fb36ffa5dbed.png">

I'd appreciate if this is something you would consider. Thank you for your work.

**Comment by g-bauer** [comment]
Thanks for the issue. I hopefully fixed it - I was using inconsistent names for the tags. Could you give it another try and report back if it works for you?

**Comment by lukthony** [comment]
Works a treat! Thanks bunches 😊
<img width="313" alt="Screen Shot 2021-12-17 at 3 34 34 AM" src="https://user-images.githubusercontent.com/65358837/146522830-c517e4b1-d1cd-4827-952a-40342b7383c9.png">
